print("╔═════════════════════╗")
print("║       Toplama       ║")
print("║                     ║")
print("║  1-5+3              ║")
print("║  2-3+4              ║")
print("║  3-5+5              ║")
print("║  4-6+5              ║")
print("║  5-4+7              ║")
print("║  6-4+5              ║")
print("║  7-3+8              ║")
print("║  8-7+9              ║")
print("║  9-9+4              ║")
print("║  10-4+8             ║")
print("║     sonuç nedir?    ║")
print("╚═════════════════════╝")
