ad=input('ismin ne?')
print("merhaba", ad)
sayı1=int(input("1.sayıyı gir:"))
sayı2=int(input("2.sayıyı gir:"))
sonuc=sayı1+sayı2
print("sonuc: ",sonuc)
sayi1=input("1.sayıyı gir:")
sayi2=input("2.sayıyı gir:")
sonuc=int(sayi1)+(sayi2)
print("sonuc: ",sonuc)
